=== Å knytte en tjeneste eller hendelse til begrep [[KnytteTilBegrep]]

Spesifikasjonen utvider CPSV-AP med egenskapen «begrep» (`dct:subject`) i <<Hendelse>>, <<Livshendelse>>, <<Virksomhetshendelse>>, <<Tjeneste>> og <<OffentligTjeneste>>. Egenskapen brukes til å referere til et eller flere begreper som er relatert til hendelsen/tjenesten og som er viktig for å forstå hendelsen/tjenesten. Det anbefales å referere til begreper som er publisert i f.eks. https://data.norge.no/concepts[begrepsdelen av Felles datakatalog &#x29C9;, window="_blank", role="ext-link"]. Eksempel: begrepet ‘daglig leder’ er viktig for tjenesten «Skjenkebevilling».

Se også https://data.norge.no/specification/skos-ap-no-begrep/[SKOS-AP-NO-begrep &#x29C9;, window="_blank", role="ext-link"] for hvordan begreper beskrives og begrepsbeskrivelser tilgjengeliggjøres i maskinlesbare formater i henhold til RDF, eller https://data.norge.no/specification/tbx-ap-no[TBX-AP-NO &#x29C9;, window="_blank", role="ext-link"] for hvordan begrepsbeskrivelser tilgjengeliggjøres i maskinlesbare formater i henhold til ISO-standarden TBX.
