== Vedlegg B – Endringslogg [[Endringslogg]]

=== Fra v.1.0.x til v.1.1.0

#@@@@@@ NB! Flere endringer er på vei!#

==== Endringer av dokumentstrukturen 

:xrefstyle: short

Spesifikasjonen inneholder nå tre hoveddeler i tillegg til det innledende kapittelet og vedleggene:

* <<Forenklet-fremstilling>>  inneholder en forenklet fremstilling av de viktigste kravene i spesifikasjonen. Denne delen er primært ment for den ikke-tekniske målgruppen. 

* <<Spesifikasjon-per-klasse>>  inneholder tekniske krav til hvordan beskrivelser av tjenester, hendelser osv. skal representeres i RDF. Denne delen er primært ment for den tekniske målgruppen.  

* <<Spesielle-temaer>> inneholder forklaring/veiledning til hvordan CPSV-AP-NO er tenkt brukt i noen spesifikke brukstilfeller. Denne delen er ment for både den ikke-tekniske og den tekniske målgruppen, fortrinnsvis sammen. 

:xrefstyle: full

==== Endringer av klasser og egenskaper 

Generelt: 

* Det stilles ikke lenger krav til om en klasse er obligatorisk, anbefalt eller valgfri. Dette fordi hvilke klasser som trengs er avhengig av brukstilfelle.   

Utgåtte klasser: 

* Klassen Datasett (dcat:Dataset): Klassen er ikke eksplisitt spesifisert i denne spesifikasjonen, fordi det ikke lenger er krav til datasett som er spesifikke når det gjelder tjeneste- og hendelsesbeskrivelser. 

* Klassen Dokumentasjon (cv:Evidence) utgått, fordi CPSV-AP-NO er nå avgrenset til å støtte metadatabeskrivelser av tjenester og hendelser, mens Dokumentasjon (cv:Evidence) er ment for å representere et konkret stykke dokumentasjon oppgitt av brukeren ved utførelsen av en gitt tjeneste. Bruk <<PåkrevdDokumentasjon>> til å metadatabeskrive dokumentasjon som er påkrevd av en tjeneste. 

* Klassen Tjenesteresultat (cv:Output) utgått, fordi CPSV-AP-NO er nå avgrenset til å støtte metadatabeskrivelser av tjenester og hendelser, mens Tjenesteresultat (cv:Output) er ment for å representere et konkret stykke tjenesteresultat fra en gitt tjeneste. Bruk <<MuligTjenesteresultat>> til å metadatabeskrive mulige tjenesteresultater fra en tjeneste. 

* Klassen Understøttende opplysning (cv:SupportedValue) utgått, fordi CPSV-AP-NO er nå avgrenset til å støtte metadatabeskrivelser av tjenester og hendelser, mens Understøttende opplysning (cv:SupportedValue) er ment for å representere en konkret verdi av et informasjonsbegrep som finnes i et konkret stykke dokumentasjon oppgitt av brukeren ved utførelsen av en gitt tjeneste. 

Nye klasser: 

* <<PåkrevdDokumentasjon>>: føyet til for å kunne dekke behov for å beskrive påkrevd dokumentasjon (ettersom klassen cv:Evidence i CPSV-AP skal representere et konkret stykke dokumentasjon som brukeren oppgir ved utførelsen av tjenesten, og ikke hva som kreves av dokumentasjon).

* <<MuligTjenesteresultat>>: føyet til for å kunne dekke behov for å beskrive hva som er mulige tjenesteresultater fra en tjeneste (ettersom klassen cv:Output i CPSV-AP skal representere et konkret stykke tjenesteresultat fra en gitt tjeneste, og ikke hva som er mulige tjenesteresultater).

Endrede klasser: 

* <<Begrensning>>: 
** Egenskapen «Begrensning – har understøttende dokumentasjon (cv:hasSupportingEvidence)» utgått (som en konsekvens av at Klassen Dokumentasjon (cv:Evidence) utgår). 

* <<Hendelse>> (inkl. subklassene <<Livshendelse>> og <<Virksomhetshendelse>>): 
** Klassen er ikke lenger en subklasse av klassen Datasett (dcat:Dataset). For å kunne bl.a. publisere hendelsesstrøm, er det innført en ny egenskap <<Hendelse-beskrivendeDatasett>> som kan benyttes til å knytte en hendelse til et eller flere datasett. Tilsvarende gjelder også subklassene <<Livshendelse>> og <<Virksomhetshendelse>>. 

* <<Informasjonskrav>>: 
** Egenskapen «Informasjonskrav – har understøttende dokumentasjon (cv:hasSupportingEvidence)» utgått (som en konsekvens av at Klassen Dokumentasjon (cv:Evidence) utgår). 

* <<Krav>>:
** Egenskapen «Krav – har understøttende dokumentasjon (cv:hasSupportingEvidence)» utgått (som en konsekvens av at Klassen Dokumentasjon (cv:Evidence) utgår).

* <<Kriterium>>:
** Egenskapen «Kriterium – har understøttende dokumentasjon (cv:hasSupportingEvidence)» utgått (som en konsekvens av at Klassen Dokumentasjon (cv:Evidence) utgår).

* <<OffentligTjeneste>>: 
** Kravnivået til egenskapene <<OffentligTjeneste-harDel>> og <<OffentligTjeneste-erDelAv>> er endret fra anbefalt til valgfri. 
** Til egenskapen <<OffentligTjeneste-status>> er kravet til bruk kontrollert vokabular endret til å bruke EU's kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/distribution-status[__Distribution status__ &#x29C9;, window="_blank", role="ext-link"] (som har samme status-verdier som tidligere ADMS Status Vocabulary). 
** Egenskapene <<OffentligTjeneste-harPåkrevdDokumentasjon>> og <<OffentligTjeneste-harMuligTjenesteresultat>> føyet til, for å kunne beskrive påkrevd dokumentasjon til, og mulig tjenesteresultat fra en offentlig tjeneste.

* <<Tjeneste>>: 
** Kravnivået til egenskapene <<Tjeneste-harDel>> og <<Tjeneste-erDelAv>> er endret fra anbefalt til valgfri. 
** Til egenskapen <<Tjeneste-status>> er kravet til bruk kontrollert vokabular endret til å bruke EU's kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/distribution-status[__Distribution status__ &#x29C9;, window="_blank", role="ext-link"] (som har samme status-verdier som tidligere ADMS Status Vocabulary). 
** Egenskapene <<Tjeneste-harPåkrevdDokumentasjon>> og <<Tjeneste-harMuligTjenesteresultat>> føyet til, for å kunne beskrive påkrevd dokumentasjon til, og mulig tjenesteresultat fra en tjeneste.

* <<Tjenestekanal>>: 
** <<Tjenestekanal-harPåkrevdDokumentasjon>> føyet til for å kunne beskrive dokumentasjon som er påkrevd av tjenestekanalen. 

=== Fra v.1.0.3 til v.1.0.x

Kun redaksjonelle oppdateringer, for å rette opp skrivefeil, uoverensstemmelser mellom tekst og tegning, upresise formuleringer og lignende. 

=== Fra v.1.0.2 til v.1.0.3

Klassen time:DayOfWeek er utvidet med schema:PublicHolidays, slik at det blir lettere å bruke egenskapen time:dayOfWeek til å spesifisere (begrenset) åpningstid for offentlige helligdager. 

=== Fra v.1.0 til v.1.0.2

Kun redaksjonelle oppdateringer, dvs. å rette opp skrivefeil, uoverensstemmelser mellom tekst og tegning, upresise formuleringer og lignende. 
