== Vedlegg B – Endringslogg [[Endringslogg]]

=== Fra v1.1 til v.2

Hovedsakelig:

. Hvordan beskrive krav og kravoppfyllelse er skilt ut i en egen «Spesifikasjon for beskrivelse av krav og kravoppfyllelse (CCCEV-AP-NO)» som er https://informasjonsforvaltning.github.io/cccev-ap-no/[under utarbeidelse &#x29C9;, window="_blank", role="ext-link"]. Dette for å gjøre CPSV-AP-NO mer fokusert på beskrivelse av tjenester og hendelser, slik at CPSV-AP-NO blir enklere å bruke for de fleste.

. <<Forenklet-fremstilling>> inneholder nå også krav i prosatekst som er formulert uavhengig av hvordan de implementeres. Dette for å gjøre CPSV-AP-NO mer tilgjengelig for den ikke-tekniske målgruppen, og for å gjøre det enklere å forstå hva som er kravene i denne standarden, uten å måtte forstå tekniske detaljer om RDF-representasjon.

. Klasser som er tatt ut:
** Klassene «Begrensning (`cv:Constraint`)», «Dokumentasjonstypeliste (`cv:EvidenceTypeList`)», «Informasjonsbegrep (`cv:InformationConcept`)», «Informasjonskrav (`cv:InformationRequirement`)», «Krav (`cv:Requirement`)», «Kriterium (`cv:Criterion`)» og «Referanserammeverk (`cv:ReferenceFramework`)» er tatt ut av CPSV-AP-NO, og inn i en egen, separat https://informasjonsforvaltning.github.io/cccev-ap-no/[Spesifikasjon for beskrivelse av krav og kravoppfyllelse (CCCEV-AP-NO) &#x29C9;, window="_blank", role="ext-link"].
** Klassen «Mulig tjenesteresultat (`cpsvno:PossibleOutput`)» er utgått og skal ikke brukes lenger. Klassen «<<Tjenesteresultattype, Tjenesteresultattype (`cpsvno:OutputType`)>>» skal brukes i stedet.
** Klassen «Påkrevd dokumentasjon (`cpsvno:RequiredEvidence`)» er utgått og skal ikke brukes lenger. Klassen «<<Dokumentasjonstype, Dokumentasjonstype (`cv:EvidenceType`)>>» skal brukes i stedet.


. Klasser som er innført:
** Klassen «<<LovpålagtTjeneste, Lovpålagt tjeneste (`cpsvno:StatutoryService`)>>» er innført for å kunne beskrive lovpålagte tjenester som ikke er knyttet til gitte, konkrete tjenesteyende offentlige organisasjoner.
** Klassene «<<Tjenesteresultattype, Tjenesteresultattype (`cpsvno:OutputType`)>>» og «<<Tjenesteresultattypeliste, Tjenesteresultattypeliste (`cpsvno:OutputTypeList`)>>» er innført for å kunne beskrive typer mulige tjenesteresultater.


. Endringer av egenskaper i eksisterende klasser:
** Klassen «<<Dokumentasjonstype, Dokumentasjonstype (`cv:EvidenceType`)>>»: 
*** Egenskapen «Dokumentasjonstype – har dokumentasjonskrav (cpsv:hasInput)» er utgått (som en konsekvens av at klassen «Påkrevd dokumentasjon (cpsvno:RequiredEvidence)» utgår).
** #mer tekst kommer#

=== Fra v.1.1.1 til v.1.1.2

Bruker ikke blanke noder i RDF-eksemplene.

=== Fra v.1.0.x til v.1.1.1

Rettet opp feil i eksempelet i RDF Turtle for egenskapene <<Tidspunktbeskrivelse-dag-i-måneden>>, <<Tidspunktbeskrivelse-måned>> og <<https://data.norge.no/specification/cpsv-ap-no#Tidspunktbeskrivelse-%C3%A5r>>.

=== Fra v.1.0.x til v.1.1.0

==== Endringer av dokumentstrukturen 

:xrefstyle: short

Spesifikasjonen inneholder nå tre hoveddeler i tillegg til det innledende kapittelet og vedleggene:

* <<Forenklet-fremstilling>>  inneholder en forenklet fremstilling av de viktigste kravene i spesifikasjonen. Denne delen er primært ment for den ikke-tekniske målgruppen. 

* <<Spesifikasjon-per-klasse>>  inneholder tekniske krav til hvordan beskrivelser av tjenester, hendelser osv. skal representeres i RDF. Denne delen er primært ment for den tekniske målgruppen.  

* <<Spesielle-temaer>> inneholder forklaring/veiledning til hvordan CPSV-AP-NO er tenkt brukt i noen spesifikke brukstilfeller. Denne delen er ment for både den ikke-tekniske og den tekniske målgruppen, fortrinnsvis sammen. 

:xrefstyle: full

==== Endringer av klasser og egenskaper 

Generelt: 

* Det stilles ikke lenger krav til om en klasse er obligatorisk, anbefalt eller valgfri. Dette fordi hvilke klasser som trengs er avhengig av brukstilfelle.   

Utgåtte klasser: 

* Klassen «Datasett (dcat:Dataset)»: Klassen er ikke eksplisitt spesifisert i denne spesifikasjonen, fordi det ikke lenger er krav til datasett som er spesifikke når det gjelder tjeneste- og hendelsesbeskrivelser. 

* Klassen «Dokumentasjon (cv:Evidence)» er utgått, fordi CPSV-AP-NO er nå avgrenset til å støtte metadatabeskrivelser av tjenester og hendelser, mens «Dokumentasjon (cv:Evidence)» er ment for å representere et konkret stykke dokumentasjon oppgitt av brukeren ved utførelsen av en gitt tjeneste. Bruk klassen «Påkrevd dokumentasjon» til å metadatabeskrive dokumentasjon som er påkrevd av en tjeneste. 

* Klassen «Tjenesteresultat (cv:Output)» er utgått, fordi CPSV-AP-NO er nå avgrenset til å støtte metadatabeskrivelser av tjenester og hendelser, mens «Tjenesteresultat (cv:Output)» er ment for å representere et konkret stykke tjenesteresultat fra en gitt tjeneste. Bruk klassen «Mulig tjenesteresultat» til å metadatabeskrive mulige tjenesteresultater fra en tjeneste. 

* Klassen «Understøttende opplysning (cv:SupportedValue)» er utgått, fordi CPSV-AP-NO er nå avgrenset til å støtte metadatabeskrivelser av tjenester og hendelser, mens «Understøttende opplysning (cv:SupportedValue)» er ment for å representere en konkret verdi av et informasjonsbegrep som finnes i et konkret stykke dokumentasjon oppgitt av brukeren ved utførelsen av en gitt tjeneste. 

Nye klasser: 

* Klassen «Påkrevd dokumentasjon (cpsvno:RequiredEvidence)» er føyet til for å kunne dekke behov for å beskrive påkrevd dokumentasjon (ettersom klassen «Dokumentasjon (cv:Evidence)» i CPSV-AP skal representere et konkret stykke dokumentasjon som brukeren oppgir ved utførelsen av tjenesten, og ikke hva som kreves av dokumentasjon).

* Klassen «Mulig tjenesteresultat (cpsvno:PossibleOutput)» er føyet til for å kunne dekke behov for å beskrive hva som er mulige tjenesteresultater fra en tjeneste (ettersom klassen «Tjenesteresultat (cv:Output)» i CPSV-AP skal representere et konkret stykke tjenesteresultat fra en gitt tjeneste, og ikke hva som er mulige tjenesteresultater).

Endrede klasser: 

* Klassen «Begrensning (cccev:Constraint)»: 
** Egenskapen «Begrensning – har understøttende dokumentasjon (cv:hasSupportingEvidence)» er utgått (som en konsekvens av at klassen «Dokumentasjon (cv:Evidence)» utgår). 

* <<Hendelse>> (inkl. subklassene <<Livshendelse>> og <<Virksomhetshendelse>>): 
** Klassen er ikke lenger en subklasse av klassen «Datasett (dcat:Dataset)». For å kunne bl.a. publisere hendelsesstrøm, er det innført en ny egenskap <<Hendelse-er-beskrevet-ved>> som kan benyttes til å knytte en hendelse til et eller flere datasett. Tilsvarende gjelder også subklassene <<Livshendelse>> og <<Virksomhetshendelse>>. 

* Klassen «Informasjonskrav (cv:InformationRequirement)»: 
** Egenskapen «Informasjonskrav – har understøttende dokumentasjon (cv:hasSupportingEvidence)» er utgått (som en konsekvens av at klassen «Dokumentasjon (cv:Evidence)» utgår). 

* Klassen «Krav (cv:Requirement)»:
** Egenskapen «Krav – har understøttende dokumentasjon (cv:hasSupportingEvidence)» er utgått (som en konsekvens av at klassen «Dokumentasjon (cv:Evidence)» utgår).

* Klassen «Kriterium (cv:Criterion)»:
** Egenskapen «Kriterium – har understøttende dokumentasjon (cv:hasSupportingEvidence)» er utgått (som en konsekvens av at klassen «Dokumentasjon (cv:Evidence)» utgår).

* <<OffentligTjeneste>>: 
** Kravnivået til egenskapene <<OffentligTjeneste-har-del>> og <<OffentligTjeneste-er-del-av>> er endret fra anbefalt til valgfri. 
** Til egenskapen <<OffentligTjeneste-status>> er kravet til bruk kontrollert vokabular endret til å bruke EUs kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/distribution-status[__Distribution status__ &#x29C9;, window="_blank", role="ext-link"] (som har samme status-verdier som tidligere ADMS Status Vocabulary). 
** Egenskapene «Offentlig tjeneste - har påkrevd dokumentasjon (cpsvno:hasRequiredEvidence)» og «Offentlig tjeneste- har mulig tjenesteresultat (cpsvno:hasPossibleOutput)» er føyet til, for å kunne beskrive påkrevd dokumentasjon til, og mulig tjenesteresultat fra en offentlig tjeneste.
** Egenskapene «Offentlig tjeneste – har dokumentasjonskrav (cpsv:hasInput)» og «Offentlig tjeneste – produserer (cpsv:produces)» er utgått (som en konsekvens av at klassene «Dokumentasjon (cv:Evidence)» og «Tjenesteresultat (cv:Output)» utgår). 

* <<Tjeneste>>: 
** Kravnivået til egenskapene <<Tjeneste-har-del>> og <<Tjeneste-er-del-av>> er endret fra anbefalt til valgfri. 
** Til egenskapen <<Tjeneste-status>> er kravet til bruk kontrollert vokabular endret til å bruke EUs kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/distribution-status[__Distribution status__ &#x29C9;, window="_blank", role="ext-link"] (som har samme status-verdier som tidligere ADMS Status Vocabulary). 
** Egenskapene «Tjeneste - har påkrevd dokumentasjon (cpsvno:hasRequiredEvidence)» og «Tjeneste- har mulig tjenesteresultat (cpsvno:hasPossibleOutput) er føyet til, for å kunne beskrive påkrevd dokumentasjon til, og mulig tjenesteresultat fra en tjeneste.
** Egenskapene «Tjeneste – har dokumentasjonskrav (cpsv:hasInput)» og «Tjeneste – produserer (cpsv:produces)» er utgått (som en konsekvens av at klassene «Dokumentasjon (cv:Evidence)» og «Tjenesteresultat (cv:Output)» utgår). 

* <<Tjenestekanal>>: 
** Egenskapen «Tjenestekanal - har påkrevd dokumentasjon (cpsvno:hasRequiredEvidence)» er føyet til for å kunne beskrive dokumentasjon som er påkrevd av tjenestekanalen. 

=== Fra v.1.0.3 til v.1.0.x

Kun redaksjonelle oppdateringer, for å rette opp skrivefeil, uoverensstemmelser mellom tekst og tegning, upresise formuleringer og lignende. 

=== Fra v.1.0.2 til v.1.0.3

Klassen time:DayOfWeek er utvidet med schema:PublicHolidays, slik at det blir lettere å bruke egenskapen time:dayOfWeek til å spesifisere (begrenset) åpningstid for offentlige helligdager. 

=== Fra v.1.0 til v.1.0.2

Kun redaksjonelle oppdateringer, dvs. å rette opp skrivefeil, uoverensstemmelser mellom tekst og tegning, upresise formuleringer og lignende. 
