== Vedlegg B – Endringslogg [[Endringslogg]]

=== Fra v.1.0.x til v.1.1.0

#@@@@@@ NB! Flere endringer er på vei!#

==== Endringer av dokumentstrukturen 

:xrefstyle: short

Spesifikasjonen inneholder nå tre hoveddeler i tillegg til det innledende kapittelet og vedleggene:

* <<Forenklet-fremstilling>>  inneholder en forenklet fremstilling av de viktigste kravene i spesifikasjonen. Denne delen er primært ment for den ikke-tekniske målgruppen. 

* <<Spesifikasjon-per-klasse>>  inneholder tekniske krav til hvordan beskrivelser av tjenester, hendelse osv. skal representeres i RDF. Denne delen er primært ment for den tekniske målgruppen.  

* <<Spesielle-temaer>> inneholder forklaring/veiledning til hvordan CPSV-AP-NO er tenkt brukt i noen spesifikke brukstilfeller. Denne delen er ment for både den ikke-tekniske og den tekniske målgruppen, fortrinnsvis sammen. 

:xrefstyle: full

==== Endringer av klasser og egenskaper 

Generelt: 

* Det stilles ikke lenger krav til om en klasse er obligatorisk, anbefalt eller valgfri. Dette fordi hvilke klasser som trengs er avhengig av brukstilfelle.   

Klassen Datasett (dcat:Dataset):

* Klassen er ikke eksplisitt spesifisert i denne spesifikasjonen, fordi det ikke lenger er krav til datasett som er spesifikke når det gjelder tjeneste- og hendelsesbeskrivelser. 

<<Dokumentasjon>>: 

* Klassen er ikke lenger en subklasse av klassen Datasett (dcat:Dataset). For å kunne knytte en gitt dokumentasjon til et datasett, er det innført en ny egenskap <<Dokumentasjon-er-del-av>>. 

<<Hendelse>> (inkl. subklassene <<Livshendelse>> og <<Virksomhetshendelse>>):

* Klassen er ikke lenger en subklasse av klassen Datasett (dcat:Dataset). For å kunne bl.a. publisere hendelsesstrøm, er det innført en ny egenskap <<Hendelse-beskrivendeDatasett>> som kan benyttes til å knytte en hendelse til et eller flere datasett. Tilsvarende gjelder også subklassene <<Livshendelse>> og <<Virksomhetshendelse>>. 

<<OffentligTjeneste>>: 

* Kravnivået til egenskapene <<OffentligTjeneste-harDel>> og <<OffentligTjeneste-erDelAv>> er endret fra anbefalt til valgfri. 
* Til egenskapen <<OffentligTjeneste-status>> er kravet til bruk kontrollert vokabular endret til å bruke EU's kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/distribution-status[__Distribution status__ &#x29C9;, window="_blank", role="ext-link"] (som har samme status-verdier som tidligere ADMS Status Vocabulary). 

<<Tjeneste>>: 

* Kravnivået til egenskapene <<Tjeneste-harDel>> og <<Tjeneste-erDelAv>> er endret fra anbefalt til valgfri. 
* Til egenskapen <<Tjeneste-status>> er kravet til bruk kontrollert vokabular endret til å bruke EU's kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/distribution-status[__Distribution status__ &#x29C9;, window="_blank", role="ext-link"] (som har samme status-verdier som tidligere ADMS Status Vocabulary). 

<<Tjenesteresultat>>: 

* Klassen har ikke lenger Datasett (dcat:Dataset) som sin subklasse. For å kunne knytte et gitt tjenesteresultat til et datasett, er det innført en ny egenskap <<Tjenesteresultat-er-del-av>>. 

=== Fra v.1.0.3 til v.1.0.x

Kun redaksjonelle oppdateringer, for å rette opp skrivefeil, uoverensstemmelser mellom tekst og tegning, upresise formuleringer og lignende. 

=== Fra v.1.0.2 til v.1.0.3

Klassen time:DayOfWeek er utvidet med schema:PublicHolidays, slik at det blir lettere å bruke egenskapen time:dayOfWeek til å spesifisere (begrenset) åpningstid for offentlige helligdager. 

=== Fra v.1.0 til v.1.0.2

Kun redaksjonelle oppdateringer, dvs. å rette opp skrivefeil, uoverensstemmelser mellom tekst og tegning, upresise formuleringer og lignende. 
