== Vedlegg B – Endringslogg [[Endringslogg]]

=== Fra v.1.0.x til v.1.1.0

#@@@@@@ NB! Flere endringer er på vei!#

==== Endringer av dokumentstrukturen 

:xrefstyle: short

Spesifikasjonen inneholder nå tre hoveddeler i tillegg til det innledende kapittelet og vedleggene:

* <<Forenklet-fremstilling>>  inneholder en forenklet fremstilling av de viktigste kravene i spesifikasjonen. Denne delen er primært ment for den ikke-tekniske målgruppen. 

* <<Spesifikasjon-per-klasse>>  inneholder tekniske krav til hvordan beskrivelser av tjenester, hendelse osv. skal representeres i RDF. Denne delen er primært ment for den tekniske målgruppen.  

* <<Spesielle-temaer>> inneholder forklaring/veiledning til hvordan CPSV-AP-NO er tenkt brukt i noen spesifikke brukstilfeller. Denne delen er ment for både den ikke-tekniske og den tekniske målgruppen, fortrinnsvis sammen. 

:xrefstyle: full

==== Endringer av klasser og egenskaper 

<<Dokumentasjon>>: 

* Klassen er ikke lenger en subklasse av klassen Datasett (dcat:Dataset). For å kunne knytte en gitt dokumentasjon til et datasett, er det innført en ny egenskap <<Dokumentasjon-er-del-av>>. 

<<OffentligTjeneste>>: 

* Kravnivået til egenskapene <<OffentligTjeneste-harDel>> og <<OffentligTjeneste-erDelAv>> er endret fra anbefalt til valgfri. 

<<Tjeneste>>: 

* Kravnivået til egenskapene <<Tjeneste-harDel>> og <<Tjeneste-erDelAv>> er endret fra anbefalt til valgfri. 

<<Tjenesteresultat>>: 

* Klassen har ikke lenger Datasett (dcat:Dataset) som sin subklasse. For å kunne knytte et gitt tjenesteresultat til et datasett, er det innført en ny egenskap <<Tjenesteresultat-er-del-av>>. 

=== Fra v.1.0.3 til v.1.0.x

Kun redaksjonelle oppdateringer, for å rette opp skrivefeil, uoverensstemmelser mellom tekst og tegning, upresise formuleringer og lignende. 

=== Fra v.1.0.2 til v.1.0.3

Klassen time:DayOfWeek er utvidet med schema:PublicHolidays, slik at det blir lettere å bruke egenskapen time:dayOfWeek til å spesifisere (begrenset) åpningstid for offentlige helligdager. 

=== Fra v.1.0 til v.1.0.2

Kun redaksjonelle oppdateringer, dvs. å rette opp skrivefeil, uoverensstemmelser mellom tekst og tegning, upresise formuleringer og lignende. 
