== Om spesifikasjonen [[OmSpesifikasjonen]]

=== Formål [[Formål]]

Formålet med spesifikasjonen er å legge til rette for en felles måte å beskrive tjenester og hendelser og en felles måte å utveksle beskrivelsene. Spesifikasjonen skal bidra til å sikre interoperabilitet av kataloger/beskrivelser av tjenester og hendelser, på tvers av sektorer. Spesifikasjonen muliggjør også maskinell tilgang til beskrivelser av tjenester og hendelser.

Spesifikasjonen inngår i https://www.digdir.no/3626[Rammeverk for informasjonsforvaltning &#x29C9;, window="_blank", role="ext-link"].

=== Omfang og avgrensing [[Omfang-og-avgrensing]]

Spesifikasjonen er anbefalt brukt til å beskrive tjenester og hendelser samt å utveksle/tilgjengeliggjøre beskrivelsene. I konteksten av denne spesifikasjonen, er en hendelse en endring hos en aktør som kan utløse behov for en eller flere tjenester, dvs. ikke en hvilken som helst hendelse.

Spesifikasjonen er basert EUs https://semiceu.github.io/CPSV-AP/releases/3.1.1/[CPSV-AP v.3.1.1 &#x29C9;, window="_blank", role="ext-link"] (__Core Public Service Vocabulary Application Profile__). I tillegg til beskrivelser av offentlige tjenester som CPSV-AP dekker, dekker spesifikasjonen også behovet for å beskrive tjenester som ikke er offentlige tjenester, men som f.eks. er involvert i sammenhengende tjenester fra det offentlige.

Spesifikasjonen inneholder også engelske navn (English name) og beskrivelser (Usage note). Det gjøres oppmerksom på at ikke alle engelske navn eller beskrivelser er ordrett sitater fra EUs originale engelske tekster. Vi kan ha valgt en annen tekst til å formidle det samme budskapet på, med mindre vi eksplisitt sier at det er et avvik (dvs. også i meningsinnholdet).

Ettersom spesifikasjonen er basert på https://www.w3.org/RDF/[RDF &#x29C9;, window="_blank", role="ext-link"], vil beskrivelsene i henhold til spesifikasjonen også være RDF-baserte og dermed maskinprosesserbare. Som støtte til teknisk implementering er det i spesifikasjonen også tatt med en del eksempler i RDF Turtle. Eksemplene i RDF Turtle er kun veiledende, de er ikke komplette og kan også mangle verdier til obligatoriske egenskaper.

=== Målgrupper [[Målgrupper]]

Spesifikasjonen har ikke sluttbrukere av tjenester som sin målgruppe, men

* deg som skal beskrive
** din virksomhets tjenester overfor innbyggere, næringsliv og sivilsamfunnet ellers
** hendelser som kan utløse behov for din eller andre virksomheters tjenester
** sammenhengende tjenester (kjeder av tjenester som eies av flere virksomheter)
** hendelser (f.eks. livshendelser) som kan utløse behov for tjenester fra flere virksomheter
* deg som søker etter og ønsker å gjenbruke / sette sammen tjenester fra andre virksomheter
* deg som skal utvikle/tilpasse verktøystøtte for ovennevnte beskrivelser og/eller for tilgjengeliggjøring/utveksling av beskrivelsene


=== Forvaltningsregime [[Forvaltningsregime]]

Spesifikasjonen forvaltes av https://digdir.no[Digitaliseringsdirektoratet (Digdir) &#x29C9;, window="_blank", role="ext-link"].

Utarbeidelse av nye versjoner av spesifikasjonen initieres av Digdir. Mindre endringer håndteres av Digdir. Ved behov for større endringer vil Digdir sette sammen arbeidsgruppe med representanter fra relevante virksomheter, for utarbeidelse av forslag til den reviderte versjonen som sendes ut til bred kommentering før fastsetting.

=== Om kravnivåene i spesifikasjonen [[Om-kravene]]

Spesifikasjonen bruker ordene «obligatorisk», «anbefalt» og «valgfri». Disse er forklart i https://data.norge.no/specification/dcat-ap-no/#Om-kravene[DCAT-AP-NO &#x29C9;, window="_blank", role="ext-link"], og forklaringene gjentas ikke her.

include::Navnerom.adoc[]

include::Leseveiledning.adoc[]
