== Om spesifikasjonen [[OmSpesifikasjonen]]

=== Formål [[Formål]]

Formålet med spesifikasjonen er å legge til rette for en felles måte å beskrive tjenester og hendelser og en felles måte for å utveksle beskrivelsene. Spesifikasjonen skal bidra til å sikre interoperabilitet av kataloger/beskrivelser av tjenester og hendelser, på tvers av sektorer. Spesifikasjonen muliggjør også maskinell tilgang til beskrivelser av tjenester og hendelser.

Spesifikasjonen inngår i https://www.digdir.no/informasjonsforvaltning/rammeverk-informasjonsforvaltning/2118[Rammeverk for informasjonsforvaltning].

=== Omfang og avgrensing [[Omfang-og-avgrensing]]

Spesifikasjonen er anbefalt brukt til å beskrive tjenester og hendelser samt å utveksle/tilgjengeliggjøre beskrivelsene. I konteksten av denne spesifikasjonen, er en hendelse en endring hos en aktør som kan utløse behov for en eller flere offentlige tjenester, dvs. ikke en hvilken som helst hendelse. Spesifikasjonen dekker også behovet for å beskrive private tjenester som f.eks. er involvert i sammenhengende tjenester fra det offentlige.

Spesifikasjonen er basert EUs https://ec.europa.eu/isa2/solutions/core-public-service-vocabulary-application-profile-cpsv-ap_en[CPSV-AP] (_Core Public Service Vocabulary Application Profile_).

Spesifikasjonen inneholder også engelske navn (English name) og beskrivelser (Usage note). Det gjøres oppmerksom på at engelske navn eller beskrivelser ikke alle er ordrett sitat fra EUs originale engelske tekster. Vi kan ha valgt en annen tekst til å formidle det samme budskapet på, med mindre vi eksplisitt sier at det er et avvik (dvs. også i meningsinnholdet).

Ettersom spesifikasjonen er basert på https://www.w3.org/RDF/[RDF] (se «Introduksjon til RDF» som er #under utarbeidelse#), vil beskrivelsene i henhold til spesifikasjonen også være RDF-baserte og dermed maskinprosesserbare. Som støtte til teknisk implementering er det i spesifikasjonen også tatt med en del eksempler i RDF Turtle. Eksemplene i RDF Turtle er kun veiledende, de er ikke komplette og kan også mangle verdier til obligatoriske egenskaper.

=== Målgrupper [[Målgrupper]]

Spesifikasjonen har ikke sluttbrukere av (offentlige) tjenester som sin målgruppe, men

* deg som skal beskrive
** din virksomhets tjenester overfor innbyggere, næringsliv og sivilsamfunnet ellers,
** hendelser som kan utløse behov for din eller andre virksomheters tjenester,
** sammenhengende tjenester (kjeder av tjenester som eies av flere virksomheter),
** hendelser (f.eks. livshendelser) som kan utløse behov for tjenester fra flere virksomheter,
* deg som søker etter og ønsker å gjenbruke / sette sammen tjenester fra andre virksomheter,
* deg som skal utvikle/tilpasse verktøystøtte for ovennevnte beskrivelser og/eller for tilgjengeliggjøring/utveksling av beskrivelsene.


=== Forvaltningsregime [[Forvaltningsregime]]

Spesifikasjonen forvaltes av https://digdir.no[Digitaliseringsdirektoratet (Digdir)].

Utarbeidelse av nye versjoner av spesifikasjonen initieres av Digdir. Mindre endringer håndteres av Digdir med ev. konsultasjon med enkelte ressurspersoner utenfor Digdir. Ved behov for større endringer vil Digdir vurdere å sette sammen arbeidsgruppe med representanter fra relevante virksomheter, for utarbeidelse av forslag til den reviderte versjonen som ev. sendes ut til bred kommentering før fastsetting.

=== Om kravene i spesifikasjonen [[Om-kravene]]

Spesifikasjonen bruker kravsnivåene «obligatorisk», «anbefalt» og «valgfri». Disse har tilsvarende betydning som i https://data.norge.no/specification/dcat-ap-no/#Om-kravene[DCAT-AP-NO] og gjentas derfor ikke her.

=== Navnerom som er brukt i spesifikasjonen [[Navnerom]]

Navnerom for dette vokabularet er: `\https://data.norge.no/vocabulary/cpsvno#`

[cols="10s,45d,45d"]
|===
|Prefiks |*Navnerom* |*Forklaring/navn*
|adms|http://www.w3.org/ns/adms[http://www.w3.org/ns/adms#] |https://www.w3.org/TR/vocab-adms/[Asset Description Metadata Schema]
|cccev|http://data.europa.eu/m8g/cccev/|https://semiceu.github.io/CCCEV/releases/2.00/[Core Criterion and Core Evidence Vocabulary]
|cpsvno|https://data.norge.no/vocabulary/cpsvno[https://data.norge.no/vocabulary/cpsvno#]|Norsk applikasjonsprofil av CPSV-AP, denne spesifikasjonen
|dcatno| \https://data.norge.no/vacabulary/dcatno#|https://data.norge.no/specification/dcat-ap-no/[Standard for beskrivelse av datasett, datatjenester og datakataloger (DCAT-AP-NO)]
|dct|http://purl.org/dc/terms/[http://purl.org/dc/terms/] |https://www.dublincore.org/specifications/dublin-core/dcmi-terms/[DCMI Metadata Terms]
|dqv|http://www.w3.org/ns/dqv# | https://www.w3.org/TR/vocab-dqv/#dqv[Data on the Web Best Practices: Data Quality Vocabulary]
|eli | \http://data.europa.eu/eli/ontology#|https://eur-lex.europa.eu/eli-register/about.html[European Legislation Identifier]
|org|http://www.w3.org/ns/org#|https://www.w3.org/TR/vocab-org/[The Organization Ontology]
|rdf|http://www.w3.org/1999/02/22-rdf-syntax-ns[http://www.w3.org/1999/02/22-rdf-syntax-ns#] |https://www.w3.org/TR/rdf-syntax-grammar/[RDF 1.1 XML Syntax]
|rdfs|http://www.w3.org/2000/01/rdf-schema[http://www.w3.org/2000/01/rdf-schema#]|https://www.w3.org/TR/rdf-schema/[RDF Schema 1.1]
|schema|http://schema.org/[http://schema.org/] |https://schema.org/[Schema.org]
|skos|http://www.w3.org/2004/02/skos/core[http://www.w3.org/2004/02/skos/core#]|https://www.w3.org/TR/skos-reference/[SKOS Simple Knowledge Organization System]
|time|http://www.w3.org/2006/time[http://www.w3.org/2006/time#] |https://www.w3.org/TR/owl-time/[Time Ontology in OWL]
|xsd|http://www.w3.org/2001/XMLSchema[http://www.w3.org/2001/XMLSchema#] |https://www.w3.org/TR/xmlschema-2/[XML Schema Part 2: Datatypes Second Edition]
|===
