name: build pylode

on:
  push:
    branches:
    - master

jobs:
  pylode_build:
    runs-on: ubuntu-18.04
    name: pylode build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64

    - name: Install dependencies
      run: |
        pip install pylode

    - name: check for changes
      run: |
        mkdir build

    - name: Build html
      run: pylode -i ontology/cpsvno.ttl -o build/index.html -p vocpub

    - name: copy cpsvno.ttl
      uses: canastro/copy-file-action@master
      with:
        source: "ontology/cpsvno.ttl"
        target: "build/cpsvno.ttl"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: html
        publish_dir: ./build
